# Generated by Django 5.1.4 on 2024-12-26 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_students_delete_usersanswers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Students",
            new_name="AnswerStudent",
        ),
    ]
